CREATE DATABASE QUAN_LY_CUA_HANG;
USE QUAN_LY_CUA_HANG;

-- Tuần 1:
-- I. Ngôn ngữ định nghĩa dữ liệu (Data Definition Language)
-- CAU 1:
CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	DOANHSO MONEY,
	NGDK SMALLDATETIME,
);

CREATE TABLE NHANVIEN
(
	MANV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME,
);

CREATE TABLE SANPHAM
(
	MASP CHAR(4) PRIMARY KEY,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY,
);

CREATE TABLE HOADON
(
	SOHD INT PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MANV CHAR(4) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	TRIGIA MONEY,
);

CREATE TABLE CTHD
(
	SOHD INT FOREIGN KEY REFERENCES HOADON(SOHD),
	MASP CHAR(4) FOREIGN KEY REFERENCES SANPHAM(MASP),
	SL INT,
	CONSTRAINT PK_CTHD PRIMARY KEY (SOHD, MASP),
);

--CAU 2:
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20);

--CAU 3:
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT;

--CAU 4:
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);

--CAU 5:
ALTER TABLE SANPHAM DROP COLUMN GHICHU;

--CAU 6:
ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(100);

--CAU 7:
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_DVT CHECK (DVT IN ('cay', 'cai', 'hop', 'quyen', 'chuc'));

--CAU 8:
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_GIA CHECK (GIA >= 500);

--CAU 9:

--CAU 10:
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NGAY CHECK (NGDK > NGSINH);

-- Tuần 2:
-- II. Ngôn ngữ thao tác dữ liệu (Data Manipulation Language)
-- CAU 1:
SELECT * FROM KHACHHANG;
SELECT * FROM KHACHHANG1;
SELECT * FROM NHANVIEN;
SELECT * FROM SANPHAM;
SELECT * FROM SANPHAM1;
SELECT * FROM HOADON;
SELECT * FROM CTHD;

-- CAU 2:
SELECT * INTO SANPHAM1 FROM SANPHAM;
SELECT * INTO KHACHHANG1 FROM KHACHHANG;

-- CAU 3:
UPDATE SANPHAM1
SET GIA = GIA * 1.05
WHERE NUOCSX = 'Thai Lan';

-- CAU 4:
UPDATE SANPHAM1
SET GIA = GIA * 0.95
WHERE NUOCSX = 'Trung Quoc' AND GIA <= 10000;

--CAU 5:
SET DATEFORMAT DMY
UPDATE KHACHHANG1
SET LOAIKH = 'Vip'
WHERE	((NGDK < '1-1-2007' AND DOANHSO >= 10000000) 
		OR
		(NGDK >= '1-1-2007' AND DOANHSO >= 2000000));

-- III. Ngôn ngữ truy vấn dữ liệu:
-- CAU 1:
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc';

-- CAU 2:
SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT = 'cay' OR DVT = 'quyen';

-- CAU 3:
SELECT MASP, TENSP
FROM SANPHAM
WHERE MASP LIKE 'B%1';

-- CAU 4:
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA BETWEEN 30000 AND 40000;

-- CAU 5:
SELECT MASP, TENSP, NUOCSX, GIA
FROM SANPHAM1
WHERE (NUOCSX = 'Trung Quoc' OR NUOCSX = 'Thai Lan') AND GIA BETWEEN 30000 AND 40000;

-- CAU 6:
SELECT SOHD, TRIGIA
FROM HOADON
WHERE NGHD = '1-1-2007' OR  NGHD = '2-1-2007';

-- CAU 7: 
SELECT SOHD, TRIGIA, NGHD
FROM HOADON
WHERE NGHD BETWEEN '1-1-2007' AND '31-1-2007'
ORDER BY NGHD ASC, TRIGIA DESC;

-- CAU 8:
SELECT KH.MAKH, KH.HOTEN
FROM KHACHHANG AS KH
JOIN HOADON AS HD 
ON KH.MAKH = HD.MAKH
WHERE NGHD = '1-1-2007';

-- CAU 9:
SELECT SOHD, TRIGIA
FROM HOADON
WHERE MANV IN 
(
    SELECT MANV
    FROM NHANVIEN
    WHERE HOTEN = 'Nguyen Van B'
)
AND NGHD = '2006-10-28';

-- CAU 10:
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM 
JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
JOIN HOADON ON HOADON.SOHD = CTHD.SOHD
JOIN KHACHHANG ON KHACHHANG.MAKH = HOADON.MAKH
WHERE KHACHHANG.HOTEN = 'Nguyen Van A' AND MONTH(NGHD) = 10 AND YEAR(NGHD) = 2006

-- CAU 11:
SELECT DISTINCT CTHD.SOHD
FROM CTHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE SANPHAM.MASP IN ('BB01', 'BB02')

-- CAU 12:
SELECT CTHD.SOHD
FROM CTHD
JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE SANPHAM.MASP IN ('BB01', 'BB02') AND CTHD.SL BETWEEN 10 AND 20

-- CAU 13:
SELECT SOHD
FROM CTHD
WHERE (MASP IN ('BB01', 'BB02') AND SL BETWEEN 10 AND 20)
GROUP BY SOHD
HAVING COUNT(MASP) = 2;

-- CAU 14:
SELECT *
FROM SANPHAM
JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
JOIN HOADON ON HOADON.SOHD = CTHD.SOHD
WHERE SANPHAM.NUOCSX = 'Trung Quoc' OR NGHD = '1-1-2007'

-- CAU 15:
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM
LEFT JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
WHERE CTHD.MASP IS NULL

-- CAU 16:
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM
LEFT JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
JOIN HOADON ON HOADON.SOHD = CTHD.SOHD
WHERE CTHD.MASP IS NULL AND YEAR(NGHD) = 2006

-- CAU 17:
SELECT SANPHAM.MASP, SANPHAM.TENSP
FROM SANPHAM
LEFT JOIN CTHD ON CTHD.MASP = SANPHAM.MASP
JOIN HOADON ON HOADON.SOHD = CTHD.SOHD
WHERE CTHD.MASP IS NULL AND YEAR(HOADON.NGHD) = 2006 AND SANPHAM.NUOCSX = 'Trung Quoc'

-- CAU 18:
SELECT *
FROM CTHD
WHERE NOT EXISTS 
(
	SELECT *
	FROM CTHD
    WHERE NOT EXISTS 
	(
		SELECT *
		FROM SANPHAM
		WHERE CTHD.MASP = SANPHAM.MASP AND SANPHAM.NUOCSX = 'Singapore'
	)
);

-- CAU 19:

-- CAU 20:
SELECT COUNT(*) AS KH_KhongPhaiThanhVien
FROM HOADON
WHERE MAKH IS NULL;

-- CAU 21:
SELECT COUNT(DISTINCT MASP) AS SP_KHACNHAU
FROM CTHD
JOIN HOADON ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR(NGHD) = 2006

-- CAU 22:
SELECT MAX(TRIGIA) AS MaxValue, MIN(TRIGIA) AS MinValue
FROM HOADON;

-- CAU 23:
SELECT AVG(TRIGIA) AS TRIGIA_TRUNGBINH
FROM HOADON
WHERE YEAR(NGHD) = 2006

-- CAU 24:
SELECT SUM(TRIGIA) AS DOANH_THU
FROM HOADON
WHERE YEAR(NGHD) = 2006

-- CAU 25:
SELECT TOP 1 SOHD
FROM HOADON
WHERE YEAR(NGHD) = 2006
ORDER BY TRIGIA DESC







