CREATE DATABASE QLP
SET DATEFORMAT dmy
USE QLP 
GO

CREATE TABLE XUONGPHIM
(
	TenXuong CHAR(20) PRIMARY KEY,
	DiaChi VARCHAR(50)
)

CREATE TABLE PHIM
(
	MaPhim CHAR(10) PRIMARY KEY,
	TenPhim CHAR(20),
	NamSX SMALLDATETIME,
	ThoiLuong INT,
	TenXuong CHAR(20) FOREIGN KEY REFERENCES XUONGPHIM(TenXuong)
)

CREATE TABLE DIENVIEN
(
	MaDV CHAR(40) PRIMARY KEY,
	TenDV CHAR(40),
	DiaChi VARCHAR(50),
	GioiTinh CHAR(3),
	NSinh DATETIME
)

CREATE TABLE DIENXUAT
(
	MaPhim CHAR(10) FOREIGN KEY REFERENCES PHIM(MaPhim),
	MaDV CHAR(40) FOREIGN KEY REFERENCES DIENVIEN(MaDV)
)

ALTER TABLE DIENVIEN ADD CONSTRAINT CK_TUOIDIENVIEN CHECK (YEAR(GETDATE()) - NSINH >= 3)
ALTER TABLE DIENVIEN ALTER COLUMN NSinh DATETIME

INSERT INTO DIENVIEN(MaDV, TenDV, DiaChi, GioiTinh, NSinh) VALUES ('DV01', 'PHUONG2', '49 Le Duan', 'NAM', '1/1/2005')


