USE QLBH_20520731;
SET DATEFORMAT DMY;

--- Phần Trigger ---
-- I.11 --
GO
CREATE TRIGGER TRG_HD_11 ON HoaDon 
FOR INSERT
AS
BEGIN
	IF (
		(
		SELECT COUNT(*) 
		FROM KhachHang KH, INSERTED INS
		WHERE KH.MAKH = INS.MAKH AND KH.NGDK>INS.NGHD 
		) > 0
	)
	BEGIN	
		PRINT 'THEM KHONG THANH CONG, NGHD < NGDK'
		ROLLBACK TRANSACTION
	END
	ELSE
		PRINT 'THEM THANH CONG'
END;

-- I.12 --
GO
CREATE TRIGGER TRG_HD_12 ON HoaDon
FOR INSERT, UPDATE 
AS 
BEGIN
	IF (
		(
		SELECT COUNT(*) 
		FROM NhanVien NV, INSERTED INS
		WHERE NV.MANV = INS.MANV AND NV.NGVL>INS.NGHD 
		) > 0
	)
	BEGIN	
		PRINT 'THEM KHONG THANH CONG, NGVL > NGHD'
		ROLLBACK TRANSACTION
	END
	ELSE
		PRINT 'THEM THANH CONG'
END;

-- 13 --
GO
CREATE TRIGGER TRG_CTHD_13 ON CTHoaDon
FOR DELETE
AS 
BEGIN
	IF (
		(
		SELECT COUNT(*) 
		FROM HoaDon HD,  DELETED DEL
		WHERE HD.SOHD = DEL.SOHD AND (
			SELECT COUNT(*)
			FROM CTHoaDon
			WHERE CTHoaDon.SOHD = HD.SOHD 
			) = 0
		) > 0
	)
	BEGIN	
		PRINT 'XOA KHONG THANH CONG, HOA DON PHAI CO IT NHAT 1 CHI TIET HOA DON'
		ROLLBACK TRANSACTION
	END
	ELSE
		PRINT 'XOA THANH CONG'
END;

-- I.14 --
GO
CREATE TRIGGER TRG_CTHD_14 ON CTHoaDon 
FOR INSERT, UPDATE, DELETE
AS
BEGIN
	UPDATE HoaDon 
	SET TRIGIA = (
		SELECT SUM(SL*GIA)
		FROM SanPham SP, CTHoaDon CT
		WHERE SP.MASP=CT.MASP AND CT.SOHD=HOADON.SOHD
		)
END;

-- I.15 --
GO
CREATE TRIGGER TRG_HD_15
ON HoaDon
AFTER INSERT
AS
BEGIN
    -- Cập nhật doanh số của khách hàng
    UPDATE KhachHang
    SET DOANHSO = DOANHSO + INS.TRIGIA
    FROM KhachHang KH
    INNER JOIN INSERTED INS ON KH.MaKH = INS.MaKH;
END;

---III.26---
SELECT DISTINCT HOTEN
FROM KhachHang, HoaDon
WHERE 
	HoaDon.MAKH = KhachHang.MAKH
	AND TRIGIA = (SELECT MAX(TRIGIA) FROM HoaDon WHERE YEAR(NGHD) = 2006)

---III.27---
SELECT TOP 3 MAKH, HOTEN
FROM KhachHang
ORDER BY DOANHSO DESC

---III.28---
SELECT MASP, TENSP
FROM SanPham
WHERE GIA IN (SELECT DISTINCT TOP 3 GIA FROM SanPham ORDER BY GIA DESC)

---III.29---
SELECT MASP, TENSP
FROM SanPham
WHERE NUOCSX = 'Thai Lan' AND GIA IN (SELECT DISTINCT TOP 3 GIA FROM SanPham ORDER BY GIA DESC)

---III.30---
SELECT MASP, TENSP
FROM SanPham
WHERE NUOCSX = 'Trung Quoc' AND GIA IN (
	SELECT DISTINCT TOP 3 GIA
	FROM SanPham
	WHERE NUOCSX = 'Trung Quoc' 
	ORDER BY GIA DESC
)

---III.31---
SELECT TOP 3 MAKH, HOTEN
FROM KhachHang
ORDER BY DOANHSO DESC

---III.32---
SELECT COUNT(DISTINCT MASP) AS 'Tổng sản phẩm do Trung Quốc sản xuất'
FROM SanPham
WHERE NUOCSX = 'Trung Quoc'

---III.33---
SELECT NUOCSX, COUNT(DISTINCT MASP) AS TONGSOSANPHAM
FROM SanPham
GROUP BY NUOCSX

---III.34---
SELECT NUOCSX, MAX(GIA) AS MAX, MIN(GIA) AS MIN, AVG(GIA) AS AVG
FROM SanPham
GROUP BY NUOCSX

---III.35---
SELECT NGHD, SUM(TRIGIA) AS DOANHTHU
FROM HoaDon
GROUP BY NGHD

---III.36---
SELECT SANPHAM.MASP, SUM(SL) SOLUONGBAN
FROM SanPham, HoaDon, CTHoaDon
WHERE
	CTHoaDon.MASP = SanPham.MASP
	AND CTHoaDon.SOHD = HoaDon.SOHD
	AND MONTH(NGHD) = 10 AND YEAR(NGHD) = 2006
GROUP BY SanPham.MASP

---III.37---
SELECT MONTH(NGHD) AS THANG, SUM(TRIGIA) AS DOANHTHU
FROM HoaDon
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)

---III.38---
SELECT SOHD
FROM CTHoaDon
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) >= 4

---III.39---
SELECT SOHD
FROM CTHoaDon, SanPham
WHERE
	CTHoaDon.MASP = SanPham.MASP
	AND NUOCSX = 'Viet Nam'
GROUP BY SOHD
HAVING COUNT(DISTINCT CTHoaDon.MASP) >= 3

---III.40---
SELECT KhachHang.MAKH, HOTEN
FROM KhachHang, HoaDon
WHERE KhachHang.MAKH = HoaDon.MAKH
GROUP BY KhachHang.MAKH, HOTEN
HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM HoaDon GROUP BY MAKH)

---III.41---
SELECT TOP 1 MONTH(NGHD) AS 'THANG DOANH SO MAX'
FROM HoaDon
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY SUM(TRIGIA) DESC

---III.42---
SELECT TOP 1 WITH TIES SanPham.MASP, TENSP
FROM SanPham, CTHoaDon, HoaDon
WHERE 
	SanPham.MASP = CTHoaDon.MASP
	AND HOADON.SOHD = CTHoaDon.SOHD
	AND YEAR(NGHD) = 2006
GROUP BY SanPham.MASP, TENSP
ORDER BY SUM(SL)

---III.43---
SELECT NUOCSX, MASP, TENSP
FROM SanPham SP1
WHERE EXISTS
(
	SELECT NUOCSX
	FROM SanPham SP2
	GROUP BY NUOCSX
	HAVING SP1.NUOCSX = SP2.NUOCSX
	AND SP1.GIA = MAX(GIA)
)

---III.44---
SELECT NUOCSX
FROM SanPham
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3

---III.45---
SELECT *
FROM KhachHang
WHERE MAKH IN
(
	SELECT TOP 1 WITH TIES HoaDon.MAKH
	FROM (SELECT TOP 10 MAKH FROM KHACHHANG ORDER BY DOANHSO DESC) AS A
	JOIN HoaDon ON A.MAKH = HoaDon.MAKH
	GROUP BY HoaDon.MAKH
	ORDER BY COUNT(*) DESC
)