CREATE DATABASE QLBH
GO
USE QLBH
GO
--CAU 2:
--1

--2
SELECT *
INTO SANPHAM1
FROM SANPHAM

SELECT *
INTO KHACHHANG1
FROM KHACHHANG
--3
UPDATE SANPHAM1
SET GIA = GIA * 1.05
WHERE NUOCSX = 'Thai Lan'
--4
UPDATE SANPHAM1
SET GIA = GIA * 1.05
WHERE NUOCSX = 'Trung Quoc'
AND GIA <= 10000
--5
UPDATE KHACHHANG1
SET LOAIKH = 'Vip'
WHERE (NGDK < 1/1/2007 AND DOANHSO >= 10000000) OR (NGDK >= 1/1/2007 AND DOANHSO >= 2000000)

--CAU 3:
--1
SELECT MASP,TENSP 
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
--2
SELECT MASP,TENSP 
FROM SANPHAM
WHERE DVT IN ('cay','quyen')
--3
SELECT MASP,TENSP 
FROM SANPHAM
WHERE MASP LIKE ('B%01')
--4
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
AND GIA BETWEEN 30000 AND 40000
--5
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX IN ('Trung Quoc','Thai Lan')
AND GIA BETWEEN 30000 AND 40000
--6
SELECT SOHD,TRIGIA,NGHD
FROM HOADON
WHERE NGHD BETWEEN '2007-01-01' AND '2007-02-01'
--7
SELECT SOHD,TRIGIA,NGHD
FROM HOADON
WHERE MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007
ORDER BY DAY(NGHD) ASC,TRIGIA DESC
--8
SELECT KH.MAHK,KH.HOTEN 
FROM HOADON AS HD,KHACHHANG AS KH 
WHERE HD.MAKH = KH.MAHK AND NGHD = '2007 - 01 -01'
--9
SELECT HD.SOHD,HD.TRIGIA 
FROM HOADON AS HD,NHANVIEN AS NV 
WHERE HD.MANV = NV.MANV AND NV.HOTEN = 'Nguyen Van B' AND HD.NGHD = '2006-10-28'
--10
SELECT DISTINCT SP.MASP,SP.TENSP
FROM CTHD AS CT,SANPHAM AS SP
WHERE CT.SOHD IN (SELECT DISTINCT HD.SOHD FROM HOADON AS HD WHERE HD.MAKH IN (SELECT DISTINCT  KH.MAHK FROM KHACHHANG AS KH WHERE HOTEN = 'Nguyen Van A'))
AND CT.MASP = SP.MASP
--11
SELECT DISTINCT SOHD
FROM CTHD AS HD
WHERE MASP IN ('BB01','BB02')
--12
SELECT DISTINCT SOHD
FROM CTHD AS HD
WHERE MASP IN ('BB01','BB02')
AND SL BETWEEN 10 AND 20
--13
SELECT SOHD
FROM CTHD AS A
WHERE MASP = 'BB01' 
AND A.SOHD IN(SELECT SOHD FROM CTHD AS B WHERE B.MASP = 'BB02')
--14
SELECT DISTINCT SANPHAM.MASP,SANPHAM.TENSP
FROM (SANPHAM JOIN CTHD ON SANPHAM.MASP = CTHD.MASP) INNER JOIN HOADON AS HD ON CTHD.SOHD = HD.SOHD
WHERE SANPHAM.NUOCSX = 'Trung Quoc'
OR HD.NGHD = '2007-01-01'
--15
SELECT DISTINCT SP.MASP
FROM SANPHAM AS SP
WHERE SP.MASP NOT IN (SELECT DISTINCT CT.MASP FROM CTHD AS CT)
--16
SELECT DISTINCT SP.MASP
FROM SANPHAM AS SP
WHERE SP.MASP NOT IN (SELECT DISTINCT CT.MASP FROM CTHD AS CT,HOADON AS HD WHERE CT.SOHD = HD.SOHD AND YEAR(HD.NGHD) = 2006)
--17
SELECT DISTINCT SP.MASP
FROM SANPHAM AS SP
WHERE SP.MASP NOT IN (SELECT DISTINCT CT.MASP FROM CTHD AS CT,HOADON AS HD WHERE CT.SOHD = HD.SOHD AND YEAR(HD.NGHD) = 2006)
AND SP.NUOCSX = 'Trung Quoc'
--18
SELECT HD.SOHD FROM HOADON AS HD WHERE NOT EXISTS
(SELECT * FROM SANPHAM AS SP WHERE SP.NUOCSX = 'Singapore' AND NOT EXISTS
(SELECT * FROM CTHD AS CT WHERE CT.MASP = SP.MASP AND HD.SOHD = CT.SOHD))
--19
SELECT HD.SOHD FROM HOADON AS HD WHERE NOT EXISTS
(SELECT * FROM SANPHAM AS SP WHERE SP.NUOCSX = 'Singapore' AND NOT EXISTS
(SELECT * FROM CTHD AS CT WHERE CT.MASP = SP.MASP AND HD.SOHD = CT.SOHD AND YEAR(HD.NGHD) = 2006))
--20
SELECT COUNT(*)
FROM  HOADON AS HD
WHERE HD.MAKH IS NULL
--21
SELECT COUNT(DISTINCT CT.MASP)
FROM CTHD AS CT,HOADON AS HD
WHERE CT.SOHD = HD.SOHD 
AND YEAR(HD.NGHD) = 2006
--22
SELECT MAX(HD.TRIGIA) AS 'HOA DON CAO NHAT',MIN(HD.TRIGIA) AS 'HOA DON THAP NHAP'
FROM HOADON AS HD
--23
SELECT SOHD,AVG(TRIGIA)
FROM HOADON AS HD	
GROUP BY SOHD
--24
SELECT SUM(TRIGIA)
FROM HOADON AS HD
WHERE YEAR(HD.NGHD) = 2006
--25
SELECT SOHD
FROM HOADON AS HD
WHERE YEAR(HD.NGHD) = 2006
AND HD.TRIGIA = (SELECT MAX(HD2.TRIGIA) FROM HOADON AS HD2)
--26
SELECT KH.HOTEN
FROM KHACHHANG AS KH,HOADON AS HD
WHERE KH.MAHK = HD.MAKH 
AND HD.SOHD 
IN (SELECT DISTINCT SOHD
FROM HOADON AS HD
WHERE YEAR(HD.NGHD) = 2006
AND HD.TRIGIA = (SELECT MAX(HD2.TRIGIA) FROM HOADON AS HD2))
--27
SELECT TT.MAKH
FROM (SELECT TOP (3) HD.MAKH,SUM(HD.TRIGIA) AS DOANHTHU
	FROM HOADON AS HD
	GROUP BY HD.MAKH
	ORDER BY DOANHTHU DESC) AS TT
--28
SELECT SP.MASP,SP.TENSP
FROM SANPHAM AS SP
WHERE SP.GIA IN(SELECT TOP(3) *
		FROM (SELECT DISTINCT SP.GIA
		FROM SANPHAM AS SP) AS TT2
		ORDER BY TT2.GIA DESC)
--29
SELECT SP.MASP,SP.TENSP
FROM SANPHAM AS SP
WHERE SP.GIA IN(SELECT TOP(3) *
		FROM (SELECT DISTINCT SP2.GIA
		FROM SANPHAM AS SP2) AS TT2
		ORDER BY TT2.GIA DESC)
AND SP.NUOCSX = 'Thai Lan'
--30
SELECT SP.MASP,SP.TENSP
FROM SANPHAM AS SP
WHERE SP.GIA IN(SELECT TOP(3) *
		FROM (SELECT DISTINCT SP2.GIA
		FROM SANPHAM AS SP2
		WHERE SP2.NUOCSX = 'Trung Quoc') AS TT2
		ORDER BY TT2.GIA DESC)
AND SP.NUOCSX = 'Trung Quoc'
--31
SELECT *
FROM KHACHHANG
WHERE DOANHSO IN(
	SELECT DISTINCT TOP(3) DOANHSO
	FROM KHACHHANG
	ORDER BY DOANHSO DESC)
--32
SELECT COUNT(*)
FROM SANPHAM AS SP
WHERE SP.NUOCSX = 'Trung Quoc'
--33
SELECT SP.NUOCSX,COUNT(*)
FROM SANPHAM AS SP
GROUP BY SP.NUOCSX
--34
SELECT SP.NUOCSX,MAX(GIA) AS 'GIA CAO NHAT',MIN(GIA) AS 'GIA THAP NHAT',AVG(GIA) AS 'TRUNG BINH'
FROM SANPHAM AS SP
GROUP BY SP.NUOCSX
--35
SELECT HD.NGHD,SUM(HD.TRIGIA)
FROM HOADON AS HD
GROUP BY HD.NGHD
--36
SELECT CT.MASP,SUM(CT.SL)
FROM CTHD AS CT
WHERE CT.SOHD IN(SELECT HD.SOHD
					FROM HOADON AS HD
					WHERE HD.NGHD BETWEEN '2006-10-1' AND '2006-10-31')
GROUP BY CT.MASP
--37
SELECT TT.THG,SUM(TT.TRIGIA)
FROM (SELECT MONTH(HD.NGHD) AS THG,HD.TRIGIA
		FROM HOADON AS HD 
		WHERE YEAR(HD.NGHD) = 2006) AS TT
GROUP BY TT.THG
--38
SELECT TT.SOHD
FROM(SELECT CT.SOHD,COUNT(*) AS TSL
	FROM CTHD AS CT
	GROUP BY CT.SOHD) AS TT
WHERE TT.TSL >= 4
--39
SELECT TT.SOHD
FROM(SELECT CT.SOHD,COUNT(*) AS TSL
	FROM CTHD AS CT,SANPHAM AS SP
	WHERE CT.MASP = SP.MASP
	AND SP.NUOCSX = 'Viet Nam'
	GROUP BY CT.SOHD) AS TT
WHERE TT.TSL >= 3
--40
SELECT TT.MAHK,TT.HOTEN
FROM(
SELECT TOP(1) KH.MAHK,KH.HOTEN,COUNT(*) AS SLM
FROM HOADON AS HD,KHACHHANG AS KH
WHERE HD.MAKH = KH.MAHK
GROUP BY KH.MAHK,KH.HOTEN
ORDER BY SLM DESC) AS TT
--41
SELECT TOP(1) TT2.THG
FROM(
SELECT TT.THG,SUM(TT.TRIGIA) AS DTT
	FROM( 
	SELECT MONTH(HD.NGHD) AS THG,HD.TRIGIA
	FROM HOADON AS HD 
	WHERE YEAR(HD.NGHD) = 2006) AS TT
	GROUP BY TT.THG	
) AS TT2
ORDER BY TT2.DTT DESC
--42
SELECT *
FROM (
SELECT CT.MASP,COUNT(*) AS SLB
FROM CTHD AS CT
WHERE CT.SOHD IN(SELECT HD.SOHD
				FROM HOADON AS HD
				WHERE YEAR(HD.NGHD) = 2006)
GROUP BY CT.MASP) AS TT2
WHERE TT2.SLB IN(
SELECT MIN(TT.SLB)
FROM(
SELECT CT.MASP,COUNT(*) AS SLB
FROM CTHD AS CT
WHERE CT.SOHD IN(SELECT HD.SOHD
				FROM HOADON AS HD
				WHERE YEAR(HD.NGHD) = 2006)
GROUP BY CT.MASP) AS TT)
--43
SELECT *
FROM SANPHAM SP
WHERE GIA = (SELECT MAX(GIA) FROM SANPHAM SP2 WHERE SP.NUOCSX = SP2.NUOCSX)
--44
SELECT TT.NUOCSX
FROM(
SELECT SP.NUOCSX,COUNT(SP.GIA) AS TSP
FROM SANPHAM AS SP
GROUP BY SP.NUOCSX) AS TT
WHERE TT.TSP >= 3
--45
SELECT KH.MAHK,HOTEN
FROM HOADON HD JOIN KHACHHANG KH ON HD.MAKH = KH.MAHK
WHERE KH.MAHK IN(
		SELECT TOP (10) MAHK
		FROM KHACHHANG 
		ORDER BY DOANHSO DESC)
GROUP BY KH.MAHK,HOTEN
HAVING COUNT(*) >= ALL(SELECT COUNT(*)
					  FROM HOADON HD1 JOIN KHACHHANG KH1 ON HD1.MAKH = KH1.MAHK
					  WHERE KH.MAHK IN(
								SELECT TOP (10) MAHK
								FROM KHACHHANG 
								ORDER BY DOANHSO DESC)
								GROUP BY KH1.MAHK)